# ReportFile
from Betsy.bie3 import *
from Betsy.bie_rules import SignalFile_rule,SignalFile2_rule,ClusterFile_rule,ClassifyFile_rule,PcaAnalysis_rule
from Betsy.bie_rules import GenesetAnalysis_rule, DiffExprFile_rule,GatherFile_rule,GseaFile_rule

ReportFile = DataType(
    'ReportFile',
    Attribute("report_type",['normalize_file','batch_effect_remove',
                            'classify','cluster','diffgenes',
                            'heatmap','geneset','all'],'normalize_file','normalize_file'),
    Attribute('preprocess',["unknown", 'illumina', "agilent", "mas5", "rma", "loess"],
                  'unknown','unknown')
    )

list_files = [ReportFile]

                                  
all_modules = [
    Module(
        'make_normalize_report',
        [SignalFile2_rule.IntensityPlot,
         SignalFile2_rule.ControlPlot,
         SignalFile2_rule.SignalFile2,
         PcaAnalysis_rule.PcaPlot,
         SignalFile2_rule.ActbPlot,
         PcaAnalysis_rule.PcaPlot],ReportFile,
         Constraint('preprocess',CAN_BE_ANY_OF,["unknown", "agilent", "mas5", "rma", "loess"],0),
         Constraint('preprocess',CAN_BE_ANY_OF,["unknown", "agilent", "mas5", "rma", "loess"],1),
         Constraint("annotate",MUST_BE,"yes",2),
         Constraint('preprocess',CAN_BE_ANY_OF,["unknown", "agilent", "mas5", "rma", "loess"],2),
         Constraint('preprocess',CAN_BE_ANY_OF,["unknown", "agilent", "mas5", "rma", "loess"],3),
         Constraint('preprocess',CAN_BE_ANY_OF,["unknown", "agilent", "mas5", "rma", "loess"],4),
         Constraint('preprocess',CAN_BE_ANY_OF,["unknown", "agilent", "mas5", "rma", "loess"],5),
         Constraint('quantile_norm',MUST_BE,'no',5),
         Constraint('combat_norm',MUST_BE,'no',5),
         Constraint('shiftscale_norm',MUST_BE,'no',5),
         Constraint('bfrm_norm',MUST_BE,'no',5),
         Constraint('dwd_norm',MUST_BE,'no',5),
         Constraint('gene_center',MUST_BE,'no',5),
         Constraint('gene_normalize',MUST_BE,'no',5),
         Constraint('unique_genes',MUST_BE,'no',5),
         Constraint('platform',MUST_BE,'no',5),
         Constraint('group_fc',MUST_BE,'no',5),
         Consequence('report_type',SET_TO,'normalize_file'),
         Consequence('preprocess',SAME_AS_CONSTRAINT)),
    
                                      
    Module(
        'make_normalize_report_illumina',
       [ SignalFile2_rule.SignalFile2,
         PcaAnalysis_rule.PcaPlot,
         PcaAnalysis_rule.PcaPlot,
         SignalFile2_rule.IntensityPlot,
         SignalFile2_rule.ActbPlot,
         SignalFile2_rule.BiotinPlot,
         SignalFile2_rule.HousekeepingPlot,
         SignalFile2_rule.Hyb_barPlot,
         SignalFile_rule.ControlFile],ReportFile,
         Constraint('preprocess',MUST_BE,'illumina',0),
         Constraint('annotate',MUST_BE,'yes'),
         Constraint('preprocess',MUST_BE,'illumina',1),
         Constraint('quantile_norm',MUST_BE,'no',1),
         Constraint('combat_norm',MUST_BE,'no',1),
         Constraint('shiftscale_norm',MUST_BE,'no',1),
         Constraint('bfrm_norm',MUST_BE,'no',1),
         Constraint('dwd_norm',MUST_BE,'no',1),
         Constraint('gene_center',MUST_BE,'no',1),
         Constraint('gene_normalize',MUST_BE,'no',1),
         Constraint('unique_genes',MUST_BE,'no',1),
         Constraint('platform',MUST_BE,'no',1),
         Constraint('group_fc',MUST_BE,'no',1),
         Constraint('preprocess',MUST_BE,'illumina',2),
         Constraint('preprocess',MUST_BE,'illumina',8),
         Constraint('format',MUST_BE,'gct',8),
         Constraint("logged",MUST_BE,'no'),
         Consequence('preprocess',SAME_AS_CONSTRAINT,0),
         Consequence('report_type',SET_TO,'normalize_file')),
    
    Module(
        'make_cluster_report',
        [ClusterFile_rule.ClusterFile,
         ClusterFile_rule.Heatmap],ReportFile,
         Consequence('report_type',SET_TO,'cluster'),
         Consequence('preprocess',SET_TO_ONE_OF,["unknown", 'illumina', "agilent", "mas5", "rma", "loess"])),
    Module(
        'make_classify_report',
        [SignalFile2_rule.SignalFile2,
         ClassifyFile_rule.ClassifyFile,
         ClassifyFile_rule.ClassifyFile,
         ClassifyFile_rule.PredictionPlot,
         ClassifyFile_rule.PredictionPlot,
         ClassifyFile_rule.PredictionPCAPlot,
         ClassifyFile_rule.ClassifyFile,
         ClassifyFile_rule.ClassifyFile,
         ClassifyFile_rule.PredictionPlot,
         ClassifyFile_rule.PredictionPlot,
         ClassifyFile_rule.PredictionPCAPlot],ReportFile,
         Constraint('contents',MUST_BE,'class0,class1,test',0),
         Constraint('logged',MUST_BE,'yes',0),
         Constraint("format",MUST_BE,'gct',0),
         Constraint("missing_values",MUST_BE,'no',0),
         Constraint("classify_alg",MUST_BE,'svm',1),
         Constraint("actual_label",MUST_BE,'yes',1),
         Constraint("classify_alg",MUST_BE,'svm',2),
         Constraint("actual_label",MUST_BE,'no',2),
         Constraint("loocv",MUST_BE,'yes',2),
         Constraint("classify_alg",MUST_BE,'svm',3),
         Constraint("actual_label",MUST_BE,'yes',3),
         Constraint("loocv",MUST_BE,'no',3),
         Constraint("classify_alg",MUST_BE,'svm',4),
         Constraint("actual_label",MUST_BE,'no',4),
         Constraint("loocv",MUST_BE,'yes',4),
         Constraint("classify_alg",MUST_BE,'svm',5),
         Constraint("actual_label",MUST_BE,'yes',5),
         Constraint("loocv",MUST_BE,'no',5),     

         Constraint("classify_alg",MUST_BE,'weighted_voting',6),
         Constraint("actual_label",MUST_BE,'yes',6),
         Constraint("loocv",MUST_BE,'no',6),
         Constraint("classify_alg",MUST_BE,'weighted_voting',7),
         Constraint("actual_label",MUST_BE,'no',7),
         Constraint("loocv",MUST_BE,'yes',7),
         Constraint("classify_alg",MUST_BE,'weighted_voting',8),
         Constraint("actual_label",MUST_BE,'yes',8),
         Constraint("loocv",MUST_BE,'no',8),
         Constraint("classify_alg",MUST_BE,'weighted_voting',9),
         Constraint("actual_label",MUST_BE,'no',9),
         Constraint("loocv",MUST_BE,'yes',9),
         Constraint("classify_alg",MUST_BE,'weighted_voting',10),
         Constraint("actual_label",MUST_BE,'yes',10),
         Constraint("loocv",MUST_BE,'no',10),     
         Consequence('report_type',SET_TO,'classify')),
    Module(
        'make_heatmap_report',
        ClusterFile_rule.Heatmap,ReportFile,
        Constraint("cluster_alg",MUST_BE,'no_cluster_alg'),
        Consequence("report_type",SET_TO,'heatmap'),
        Consequence("preprocess",SET_TO_ONE_OF,["unknown", 'illumina', "agilent", "mas5", "rma", "loess"])),
    Module(
        'make_geneset_report',
        [GenesetAnalysis_rule.GenesetAnalysis,
         GenesetAnalysis_rule.GenesetPlot],ReportFile,
         Consequence("report_type",SET_TO,'geneset'),
         Consequence("preprocess",SET_TO_ONE_OF,["unknown", 'illumina', "agilent", "mas5", "rma", "loess"])),
        
    Module(
        'make_diffgenes_report',
        [DiffExprFile_rule.DiffExprFile,DiffExprFile_rule.DiffExprFile,
         ClusterFile_rule.Heatmap,GatherFile_rule.GatherFile,
         GseaFile_rule.GseaFile],ReportFile,
         UserInput("hm_width_value",50),
         UserInput("hm_height_value",1),
         Constraint("diff_expr",MUST_BE,'t_test',0),
         Constraint("diff_expr",MUST_BE,'sam',1),
         Constraint("cluster_alg",MUST_BE,'no_cluster_alg',2),
         Constraint("hm_width",MUST_BE,"yes",2),
         Constraint("hm_height",MUST_BE,"yes",2),
         Consequence("report_type",SET_TO,'diffgenes'),
         Consequence("preprocess",SET_TO_ONE_OF,["unknown", 'illumina', "agilent", "mas5", "rma", "loess"])),
    Module(
        'make_batch_effect_report',
        [SignalFile_rule.SignalFile,SignalFile_rule.SignalFile,
         SignalFile_rule.SignalFile,SignalFile_rule.SignalFile,
         SignalFile_rule.SignalFile],ReportFile,
         Constraint("format",MUST_BE,'tdf',0),
         Constraint("logged",MUST_BE,"yes",0),
         Constraint("missing_values",MUST_BE,'no',0),
         Constraint("quantile_norm",MUST_BE,'yes',0),
         Constraint("dwd_norm",MUST_BE,'no',0),
         Constraint("bfrm_norm",MUST_BE,'no',0),
         Constraint("combat_norm",MUST_BE,'no',0),
         Constraint("shiftscale_norm",MUST_BE,'no',0),
         Constraint("format",MUST_BE,'tdf',1),
         Constraint("logged",MUST_BE,"yes",1),
         Constraint("missing_values",MUST_BE,'no',1),
         Constraint("quantile_norm",MUST_BE,'yes',1),
         Constraint("dwd_norm",MUST_BE,'yes',1),
         Constraint("bfrm_norm",MUST_BE,'no',1),
         Constraint("combat_norm",MUST_BE,'no',1),
         Constraint("shiftscale_norm",MUST_BE,'no',1),
         Constraint("format",MUST_BE,'tdf',2),
         Constraint("logged",MUST_BE,"yes",2),
         Constraint("missing_values",MUST_BE,'no',2),
         Constraint("quantile_norm",MUST_BE,'yes',2),
         Constraint("dwd_norm",MUST_BE,'no',2),
         Constraint("bfrm_norm",MUST_BE,'no',2),
         Constraint("combat_norm",MUST_BE,'no',2),
         Constraint("shiftscale_norm",MUST_BE,'yes',2),
         Constraint("format",MUST_BE,'tdf',3),
         Constraint("logged",MUST_BE,"yes",3),
         Constraint("missing_values",MUST_BE,'no',3),
         Constraint("quantile_norm",MUST_BE,'yes',3),
         Constraint("dwd_norm",MUST_BE,'no',3),
         Constraint("bfrm_norm",MUST_BE,'yes',3),
         Constraint("combat_norm",MUST_BE,'no',3),
         Constraint("shiftscale_norm",MUST_BE,'no',3),
         Constraint("format",MUST_BE,'tdf',4),
         Constraint("logged",MUST_BE,"yes",4),
         Constraint("missing_values",MUST_BE,'no',4),
         Constraint("quantile_norm",MUST_BE,'yes',4),
         Constraint("dwd_norm",MUST_BE,'no',4),
         Constraint("bfrm_norm",MUST_BE,'no',4),
         Constraint("combat_norm",MUST_BE,'yes',4),
         Constraint("shiftscale_norm",MUST_BE,'no',4),
         Consequence("report_type",SET_TO,'batch_effect_remove'),
         Consequence("preprocess",SET_TO_ONE_OF,["unknown", 'illumina', "agilent", "mas5", "rma", "loess"]))

        ]
  
        
