annotate_file(Parameters,Modules):-
    convert_parameters_file(Parameters,NewParameters),
    get_value(NewParameters,status,created,Status),
    Status=created,
    member(OldStatus,[given,created,jointed,splited]),
    get_value(NewParameters,format,unknown_format,Format),
    Format=pcl,
    get_value(NewParameters,is_logged,logged,Is_logged),
    Is_logged=logged,
    set_value(NewParameters,status,OldStatus,OldParameters),
    get_value(Parameters,annotate,no_annotate,Annotate),
    Annotate=yes_annotate,
    signal_file(OldParameters,Past_Modules),
    append(NewParameters,[annotate,yes_annotate],NewParameters1),
    Newadd=[annotate_file,NewParameters1],
    append(Past_Modules, Newadd, Modules).
