/*geneset_analysis*/
geneset_analysis(Parameters,Modules):-
    convert_parameters_geneset(Parameters,NewParameters1),
    convert_parameters_file(NewParameters1,NewParameters),
    get_value(NewParameters,is_logged,no_logged,Is_Logged),
    Is_Logged=logged,
    get_value(NewParameters,quantile,no_quantile,Quantile),
    Quantile=yes_quantile,
    get_value(NewParameters,gene_center,no_gene_center,Center),
    Center=mean,
    get_value(NewParameters,gene_normalize,no_gene_normalize,Normalize),
    Normalize=variance,
    get_value(NewParameters,unique_genes,no_unique_genes,Unique_genes),
    Unique_genes=high_var,
    signal_file(NewParameters,Past_Modules),
    get_value(NewParameters,contents,unknown_contents,Contents),
    geneset_file([contents,Contents],[]),
    Newadd=[analyze_geneset,NewParameters1],
    append(Past_Modules,Newadd,Modules).
/*-------------------------------------------------------------------*/
convert_parameters_geneset(Parameters,Parameters1):-
   convert_parameters_file(Parameters,NewParameters),
   get_value(Parameters,geneset,no_geneset,Geneset),
   not(Geneset=no_geneset),
   get_value(Parameters,allgenes,no_allgenes,Allgenes),
   member(Allgenes,[yes_allgenes,no_allgenes]),
   get_value(Parameters,automatch,no_automatch,Automatch),
   member(Automatch,[yes_automatch,no_automatch]),
   append(NewParameters,[geneset,Geneset,allgenes,Allgenes,automatch,Automatch],Parameters1).

/*-------------------------------------------------------------------*/
geneset_plot(Parameters,Modules):-
    convert_parameters_geneset(Parameters,NewParameters),
    geneset_analysis(NewParameters,Past_Modules),
    Newadd=[plot_geneset,NewParameters],
    append(Past_Modules,Newadd,Modules).